const sidebarSettings = {
  docs: [
    {
      type: 'html',
      value: 'Введение',
      className: 'sidebar-title',
    },
    "docs/introduction",
    {
      type: "category",
      label: "Движок dbt Fusion",
      collapsed: true,
      link: { type: "doc", id: "docs/fusion/fusion" },
      items: [
        "docs/fusion/fusion",
        "docs/fusion/about-fusion",
        "docs/fusion/fusion-availability",
        "docs/fusion/fusion-readiness",
        "docs/fusion/new-concepts",
        "docs/fusion/supported-features",
        "docs/fusion/get-started-fusion",
      ],
    },
    {
      type: "category",
      label: "О платформе dbt",
      link: { type: "doc", id: "docs/cloud/about-cloud/dbt-cloud-features" },
      items: [
        "docs/cloud/about-cloud/architecture",
        "docs/cloud/about-cloud/browsers",
        "docs/cloud/about-cloud/change-your-dbt-cloud-theme",
        "docs/cloud/about-cloud/dbt-cloud-features",
        "docs/cloud/about-cloud/access-regions-ip-addresses",
        "docs/cloud/about-cloud/tenancy",
      ],
    }, // About dbt Cloud directory
    {
      type: "category",
      label: "Поддерживаемые платформы",
      collapsed: true,
      link: { type: "doc", id: "docs/supported-data-platforms" },
      items: [
        "docs/supported-data-platforms",
        "docs/connect-adapters",
        "docs/trusted-adapters",
        "docs/community-adapters",
        "docs/contribute-core-adapters",
      ],
    }, // Supported data platforms directory
    {
      type: 'html',
      value: 'Начало работы',
      className: 'sidebar-title',
    },
    {
      type: "category",
      label: "Начало работы с dbt",
      collapsed: true,
      link: { type: "doc", id: "docs/get-started-dbt" },
      items: [
        "docs/get-started-dbt",
        "docs/configuration-checklist",
      ],
    }, // Get started quickstarts directory
    {
      type: "category",
      label: "Настройка dbt",
      collapsed: true,
      link: { type: "doc", id: "docs/about-setup" },
      items: [
        "docs/about-setup",
        "docs/environments-in-dbt",
        {
          type: "category",
          label: "Платформа dbt",
          collapsed: true,
          link: { type: "doc", id: "docs/cloud/about-cloud-setup" },
          items: [
            "docs/cloud/about-cloud-setup",
            "docs/cloud/account-settings",
            "docs/cloud/account-integrations",
            "docs/dbt-cloud-environments",
            "docs/cloud/migration",
            {
              type: "category",
              label: "Подключение к платформам данных",
              link: {
                type: "doc",
                id: "docs/cloud/connect-data-platform/about-connections",
              },
              items: [
                "docs/cloud/connect-data-platform/about-connections",
                "docs/cloud/connect-data-platform/connect-apache-spark",
                "docs/cloud/connect-data-platform/connect-amazon-athena",
                "docs/cloud/connect-data-platform/connect-azure-synapse-analytics",
                "docs/cloud/connect-data-platform/connect-bigquery",
                "docs/cloud/connect-data-platform/connect-databricks",
                "docs/cloud/connect-data-platform/connect-microsoft-fabric",
                "docs/cloud/connect-data-platform/connect-onehouse",
                "docs/cloud/connect-data-platform/connect-postgresql-alloydb",
                "docs/cloud/connect-data-platform/connect-redshift",
                "docs/cloud/connect-data-platform/connect-starburst-trino",
                "docs/cloud/connect-data-platform/connect-snowflake",
                "docs/cloud/connect-data-platform/connect-teradata",
              ],
            },
            {
              type: "category",
              label: "Управление доступом",
              link: {
                type: "doc",
                id: "docs/cloud/manage-access/about-user-access",
              },
              items: [
                "docs/cloud/manage-access/about-user-access",
                "docs/cloud/manage-access/invite-users",
                "docs/cloud/manage-access/mfa",
                {
                  type: "category",
                  label: "Разрешения пользователей и лицензии",
                  link: {
                    type: "doc",
                    id: "docs/cloud/manage-access/seats-and-users",
                  },
                  items: [
                    "docs/cloud/manage-access/seats-and-users",
                    "docs/cloud/manage-access/enterprise-permissions",
                    "docs/cloud/manage-access/self-service-permissions",
                  ],
                },
                {
                  type: "category",
                  label: "Разрешения окружения",
                  link: {
                    type: "doc",
                    id: "docs/cloud/manage-access/environment-permissions",
                  },
                  items: [
                    "docs/cloud/manage-access/environment-permissions",
                    "docs/cloud/manage-access/environment-permissions-setup",
                  ],
                },
                {
                  type: "category",
                  label: "Единый вход (SSO) и OAuth",
                  link: {
                    type: "doc",
                    id: "docs/cloud/manage-access/sso-overview",
                  },
                  items: [
                    "docs/cloud/manage-access/sso-overview",
                    "docs/cloud/manage-access/auth0-migration",
                    "docs/cloud/manage-access/set-up-sso-saml-2.0",
                    "docs/cloud/manage-access/set-up-sso-okta",
                    "docs/cloud/manage-access/set-up-sso-google-workspace",
                    "docs/cloud/manage-access/set-up-sso-microsoft-entra-id",
                    "docs/cloud/manage-access/scim",
                    "docs/cloud/manage-access/set-up-snowflake-oauth",
                    "docs/cloud/manage-access/set-up-databricks-oauth",
                    "docs/cloud/manage-access/set-up-bigquery-oauth",
                    "docs/cloud/manage-access/snowflake-external-oauth",
                    "docs/cloud/manage-access/redshift-external-oauth",
                  ],
                }, // SSO
                "docs/cloud/manage-access/audit-log",
              ],
            }, // Manage access

            {
              type: "category",
              label: "Настройка Git",
              link: {
                type: "doc",
                id: "docs/cloud/git/git-configuration-in-dbt-cloud",
              },
              items: [
                "docs/cloud/git/git-configuration-in-dbt-cloud",
                "docs/cloud/git/managed-repository",
                "docs/cloud/git/import-a-project-by-git-url",
                "docs/cloud/git/connect-github",
                "docs/cloud/git/connect-gitlab",
                {
                  type: "category",
                  label: "Azure DevOps",
                  link: {
                    type: "doc",
                    id: "docs/cloud/git/connect-azure-devops",
                  },
                  items: [
                    "docs/cloud/git/connect-azure-devops",
                    "docs/cloud/git/setup-service-principal",
                    "docs/cloud/git/setup-service-user",
                    "docs/cloud/git/authenticate-azure",
                  ],
                },
                {
                  type: "category",
                  label: "Система контроля версий Git",
                  link: {
                    type: "doc",
                    id: "docs/cloud/git/git-version-control",
                  },
                  items: [
                    "docs/cloud/git/git-version-control",
                    "docs/cloud/git/version-control-basics",
                    "docs/cloud/git/pr-template",
                    "docs/cloud/git/merge-conflicts",
                  ],
                },
              ],
            }, // Supported Git providers
            {
              type: "category",
              label: "Защита вашего арендатора",
              link: { type: "doc", id: "docs/cloud/secure/secure-your-tenant" },
              items: [
                "docs/cloud/secure/secure-your-tenant",
                "docs/cloud/secure/ip-restrictions",
                "docs/cloud/secure/about-private-connectivity",
                "docs/cloud/secure/snowflake-privatelink",
                "docs/cloud/secure/snowflake-private-link",
                "docs/cloud/secure/snowflake-psc",
                "docs/cloud/secure/databricks-privatelink",
                "docs/cloud/secure/databricks-private-link",
                "docs/cloud/secure/redshift-privatelink",
                "docs/cloud/secure/postgres-privatelink",
                "docs/cloud/secure/az-postgres-private-link",
                "docs/cloud/secure/az-synapse-private-link",
                "docs/cloud/secure/bigquery-psc",
                "docs/cloud/secure/vcs-privatelink",
              ],
            }, // PrivateLink
          ],
        },
        {
          type: "category",
          label: "dbt Core и Fusion",
          collapsed: true,
          link: { type: "doc", id: "docs/about-dbt-install" },
          items: [
            "docs/about-dbt-install",
            "docs/core/dbt-core-environments",
             {
              type: "category",
              label: "Установка движка dbt Fusion",
              link: { type: "doc", id: "docs/fusion/about-fusion-install" },
              items: [
                "docs/fusion/about-fusion-install",
                "docs/fusion/install-dbt-extension",
                "docs/fusion/install-fusion-cli",
              ],
            },
            {
              type: "category",
              label: "Подключение Fusion к вашей платформе данных",
              link: {
                type: "doc",
                id: "docs/fusion/connect-data-platform-fusion/profiles.yml",
              },
              items: [
                "docs/fusion/connect-data-platform-fusion/profiles.yml",
                "docs/fusion/connect-data-platform-fusion/connection-profiles",
                "docs/fusion/connect-data-platform-fusion/bigquery-setup",
                "docs/fusion/connect-data-platform-fusion/databricks-setup",
                "docs/fusion/connect-data-platform-fusion/redshift-setup",
                "docs/fusion/connect-data-platform-fusion/salesforce-data-cloud-setup",
                "docs/fusion/connect-data-platform-fusion/snowflake-setup",
              ],
            },
            {
              type: "category",
              label: "Установка dbt Core",
              link: { type: "doc", id: "docs/core/installation-overview" },
              items: [
                "docs/core/installation-overview",
                "docs/core/docker-install",
                "docs/core/pip-install",
                "docs/core/source-install",
              ],
            },
            {
              type: "category",
              label: "Подключение dbt Core к платформам данных",
              link: {
                type: "doc",
                id: "docs/core/connect-data-platform/about-core-connections",
              },
              items: [
                "docs/core/connect-data-platform/about-core-connections",
                "docs/core/connect-data-platform/profiles.yml",
                "docs/core/connect-data-platform/connection-profiles",
                "docs/core/connect-data-platform/spark-setup",
                "docs/core/connect-data-platform/bigquery-setup",
                "docs/core/connect-data-platform/databricks-setup",
                "docs/core/connect-data-platform/deltastream-setup",
                "docs/core/connect-data-platform/fabric-setup",
                "docs/core/connect-data-platform/fabricspark-setup",
                "docs/core/connect-data-platform/postgres-setup",
                "docs/core/connect-data-platform/alloydb-setup",
                "docs/core/connect-data-platform/lakebase-setup",
                "docs/core/connect-data-platform/redshift-setup",
                "docs/core/connect-data-platform/snowflake-setup",
                "docs/core/connect-data-platform/trino-setup",
                "docs/core/connect-data-platform/hive-setup",
                "docs/core/connect-data-platform/impala-setup",
                "docs/core/connect-data-platform/athena-setup",
                "docs/core/connect-data-platform/glue-setup",
                "docs/core/connect-data-platform/clickhouse-setup",
                "docs/core/connect-data-platform/cratedb-setup",
                "docs/core/connect-data-platform/databend-setup",
                "docs/core/connect-data-platform/decodable-setup",
                "docs/core/connect-data-platform/doris-setup",
                "docs/core/connect-data-platform/dremio-setup",
                "docs/core/connect-data-platform/duckdb-setup",
                "docs/core/connect-data-platform/exasol-setup",
                "docs/core/connect-data-platform/extrica-setup",
                "docs/core/connect-data-platform/firebolt-setup",
                "docs/core/connect-data-platform/greenplum-setup",
                "docs/core/connect-data-platform/ibmdb2-setup",
                "docs/core/connect-data-platform/ibmnetezza-setup",
                "docs/core/connect-data-platform/infer-setup",
                "docs/core/connect-data-platform/iomete-setup",
                "docs/core/connect-data-platform/layer-setup",
                "docs/core/connect-data-platform/materialize-setup",
                "docs/core/connect-data-platform/azuresynapse-setup",
                "docs/core/connect-data-platform/mssql-setup",
                "docs/core/connect-data-platform/mindsdb-setup",
                "docs/core/connect-data-platform/mysql-setup",
                "docs/core/connect-data-platform/oracle-setup",
                "docs/core/connect-data-platform/risingwave-setup",
                "docs/core/connect-data-platform/rockset-setup",
                "docs/core/connect-data-platform/singlestore-setup",
                "docs/core/connect-data-platform/sqlite-setup",
                "docs/core/connect-data-platform/starrocks-setup",
                "docs/core/connect-data-platform/teradata-setup",
                "docs/core/connect-data-platform/tidb-setup",
                "docs/core/connect-data-platform/upsolver-setup",
                "docs/core/connect-data-platform/vertica-setup",
                "docs/core/connect-data-platform/watsonx-presto-setup",
                "docs/core/connect-data-platform/watsonx-spark-setup",
                "docs/core/connect-data-platform/yellowbrick-setup",
                "docs/core/connect-data-platform/ydb-setup",
                "docs/core/connect-data-platform/maxcompute-setup",
              ],
            },
          ],
        },
        "docs/running-a-dbt-project/run-your-dbt-projects",
        "docs/running-a-dbt-project/using-threads",
      ],
    },
    {
      type: 'html',
      value: 'Разработка',
      className: 'sidebar-title',
    },
    {
      type: "category",
      label: "Разработка с dbt",
      collapsed: true,
      link: { type: "doc", id: "docs/cloud/about-develop-dbt" },
      items: [
        "docs/cloud/about-develop-dbt",
        "docs/about-dbt-lsp",
        "docs/cloud/about-cloud-develop-defer",
        {
          type: "category",
          label: "Расширение dbt для VS Code",
          collapsed: true,
          link: { type: "doc", id: "docs/about-dbt-extension" },
          items: [
            "docs/about-dbt-extension",
            "docs/dbt-extension-features",
            "docs/install-dbt-extension",
            "docs/configure-dbt-extension",
          ],
        },
        {
          type: "category",
          label: "dbt CLI",
          collapsed: true,
          link: { type: "doc", id: "docs/cloud/cloud-cli-installation" },
          items: [
            "docs/cloud/cloud-cli-installation",
            "docs/cloud/configure-cloud-cli",
          ],
        },
        {
          type: "category",
          label: "dbt Studio IDE",
          link: {
            type: "doc",
            id: "docs/cloud/studio-ide/develop-in-studio",
          },
          items: [
            "docs/cloud/studio-ide/develop-in-studio",
            "docs/cloud/studio-ide/ide-user-interface",
            "docs/cloud/studio-ide/keyboard-shortcuts",
            "docs/cloud/studio-ide/git-commit-signing",
            "docs/cloud/studio-ide/lint-format",
            "docs/cloud/studio-ide/autofix-deprecations",
            "docs/cloud/studio-ide/develop-copilot",
          ],
        },
        {
          type: "category",
          label: "dbt Canvas",
          collapsed: true,
          link: { type: "doc", id: "docs/cloud/canvas" },
          items: [
            "docs/cloud/canvas",
            "docs/cloud/canvas-interface",
            "docs/cloud/use-canvas",
            "docs/cloud/build-canvas-copilot",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Создание проектов",
      collapsed: true,
      link: { type: "doc", id: "docs/build/projects" },
      items: [
        "docs/build/projects",
        "docs/build/dbt-tips",
        {
          type: "category",
          label: "Создание DAG",
          collapsed: true,
          link: { type: "doc", id: "docs/build/models" },
          items: [
            {
              type: "category",
              label: "Модели",
              link: { type: "doc", id: "docs/build/models" },
              items: [
                "docs/build/models",
                "docs/build/sql-models",
                "docs/build/python-models",
              ],
            },
            {
              type: "category",
              label: "Тесты",
              link: { type: "doc", id: "docs/build/data-tests" },
              items: ["docs/build/data-tests", "docs/build/unit-tests"],
            },
            {
              type: "category",
              label: "Документация",
              link: { type: "doc", id: "docs/build/documentation" },
              items: [
                "docs/build/documentation",
                "docs/build/view-documentation",
              ],
            },
            "docs/build/snapshots",
            "docs/build/seeds",
            "docs/build/jinja-macros",
            "docs/build/udfs",
            "docs/build/sources",
            "docs/build/exposures",
            "docs/build/groups",
            "docs/build/analyses",
          ],
        },
        {
          type: "category",
          label: "Создание метрик",
          link: { type: "doc", id: "docs/build/build-metrics-intro" },
          collapsed: true,
          items: [
            "docs/build/build-metrics-intro",
            {
              type: "link",
              label: "Быстрый старт с dbt Cloud Semantic Layer",
              href: `/guides/sl-snowflake-qs`,
            },
            {
              type: "category",
              label: "О MetricFlow",
              link: { type: "doc", id: "docs/build/about-metricflow" },
              items: [
                "docs/build/about-metricflow",
                "docs/build/join-logic",
                "docs/build/metricflow-time-spine",
                "docs/build/metricflow-commands",
                "docs/build/validation",
              ],
            },
            {
              type: "category",
              label: "Семантические модели",
              link: { type: "doc", id: "docs/build/semantic-models" },
              items: [
                "docs/build/semantic-models",
                "docs/build/dimensions",
                "docs/build/entities",
                "docs/build/measures",
              ],
            },
            {
              type: "category",
              label: "Метрики",
              link: { type: "doc", id: "docs/build/metrics-overview" },
              items: [
                "docs/build/metrics-overview",
                "docs/build/conversion",
                "docs/build/cumulative",
                "docs/build/derived",
                "docs/build/ratio",
                "docs/build/simple",
              ],
            },
            "docs/build/saved-queries",
            {
              type: "category",
              label: "Продвинутое моделирование данных",
              link: { type: "doc", id: "docs/build/advanced-topics" },
              items: [
                "docs/build/fill-nulls-advanced",
                "docs/build/ref-metrics-in-filters",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Улучшение моделей",
          collapsed: true,
          link: { type: "doc", id: "docs/build/enhance-your-models" },
          items: [
            "docs/build/enhance-your-models",
            "docs/build/materializations",
            {
              type: "category",
              label: "Инкрементальные модели",
              link: {
                type: "doc",
                id: "docs/build/incremental-models-overview",
              },
              items: [
                "docs/build/incremental-models-overview",
                "docs/build/incremental-models",
                "docs/build/incremental-strategy",
                "docs/build/incremental-microbatch",
                "docs/build/parallel-batch-execution",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Улучшение кода",
          collapsed: true,
          link: { type: "doc", id: "docs/build/enhance-your-code" },
          items: [
            "docs/build/enhance-your-code",
            "docs/build/environment-variables",
            "docs/build/hooks-operations",
            "docs/build/packages",
            "docs/build/project-variables",
          ],
        },
        {
          type: "category",
          label: "Организация вывода",
          collapsed: true,
          link: { type: "doc", id: "docs/build/organize-your-outputs" },
          items: [
            "docs/build/organize-your-outputs",
            "docs/build/custom-schemas",
            "docs/build/custom-databases",
            "docs/build/custom-aliases",
            "docs/build/custom-target-names",
          ],
        },
        {
          type: "category",
          label: "Оптимизация разработки",
          collapsed: true,
          link: { type: "doc", id: "docs/build/empty-flag" },
          items: ["docs/build/empty-flag", "docs/build/sample-flag"],
        },
        //"docs/building-a-dbt-project/dont-nest-your-curlies",
        //"docs/building-a-dbt-project/archival",
      ],
    },
    {
      type: "category",
      label: "Построение dbt Mesh",
      link: { type: "doc", id: "docs/mesh/about-mesh" },
      items: [
        "docs/mesh/about-mesh",
        {
          type: "category",
          label: "Управление моделями",
          collapsed: true,
          link: {
            type: "doc",
            id: "docs/mesh/govern/about-model-governance",
          },
          items: [
            "docs/mesh/govern/about-model-governance",
            "docs/mesh/govern/model-access",
            "docs/mesh/govern/model-contracts",
            "docs/mesh/govern/model-versions",
            "docs/mesh/govern/project-dependencies",
          ],
        },
        {
          type: "category",
          label: "Apache Iceberg",
          collapsed: true,
          link: {
            type: "doc",
            id: "docs/mesh/iceberg/apache-iceberg-support",
          },
          items: [
            "docs/mesh/iceberg/apache-iceberg-support",
            "docs/mesh/iceberg/about-catalogs",
            "docs/mesh/iceberg/snowflake-iceberg-support",
            "docs/mesh/iceberg/databricks-iceberg-support",
            "docs/mesh/iceberg/bigquery-iceberg-support",
          ],
        },
      ],
    },
    {
      type: 'html',
      value: 'Развёртывание и исследование',
      className: 'sidebar-title',
    },
    {
      type: "category",
      label: "Развёртывание dbt",
      collapsed: true,
      link: { type: "doc", id: "docs/deploy/deployments" },
      items: [
        "docs/deploy/deployments",
        "docs/deploy/job-scheduler",
        "docs/deploy/deploy-environments",
        {
          type: "category",
          label: "Непрерывная интеграция (CI)",
          collapsed: true,
          link: { type: "doc", id: "docs/deploy/about-ci" },
          items: [
            "docs/deploy/about-ci",
            "docs/deploy/continuous-integration",
            "docs/deploy/advanced-ci",
          ],
        },
        "docs/deploy/continuous-deployment",
          {
          type: "category",
          label: "Учет состояния",
          link: { type: "doc", id: "docs/deploy/state-aware-about" },
          items: [
            "docs/deploy/state-aware-about",
            "docs/deploy/state-aware-setup",
            "docs/deploy/state-aware-interface",
          ],
        },
        {
          type: "category",
          label: "Работы (jobs)",
          link: { type: "doc", id: "docs/deploy/jobs" },
          items: [
            "docs/deploy/jobs",
            "docs/deploy/deploy-jobs",
            "docs/deploy/ci-jobs",
            "docs/deploy/merge-jobs",
            "docs/deploy/job-commands",
          ],
        },
        {
          type: "category",
          label: "Мониторинг и алерты",
          link: { type: "doc", id: "docs/deploy/monitor-jobs" },
          items: [
            "docs/deploy/monitor-jobs",
            "docs/deploy/orchestrate-exposures",
            "docs/deploy/artifacts",
            "docs/deploy/job-notifications",
            "docs/deploy/model-notifications",
            "docs/deploy/run-visibility",
            "docs/deploy/retry-jobs",
            "docs/deploy/source-freshness",
            "docs/deploy/webhooks",
          ],
        },
        {
          type: "category",
          label: "Гибридные проекты",
          collapsed: true,
          link: { type: "doc", id: "docs/deploy/hybrid-projects" },
          items: ["docs/deploy/hybrid-projects", "docs/deploy/hybrid-setup"],
        },
        "docs/deploy/deployment-tools",
      ],
    }, // end of "Deploy dbt"
    {
      type: "category",
      label: "Исследование данных",
      link: { type: "doc", id: "docs/explore/explore-your-data" },
      items: [
        "docs/explore/explore-your-data",
        {
          type: "category",
          label: "Обнаружение данных с помощью dbt Catalog",
          link: { type: "doc", id: "docs/explore/explore-projects" },
          items: [
            "docs/explore/explore-projects",
            "docs/explore/access-from-dbt-cloud",
            "docs/explore/column-level-lineage",
            "docs/explore/data-health-signals",
            "docs/explore/explore-multiple-projects",
            "docs/explore/external-metadata-ingestion",
            "docs/explore/global-navigation",
            "docs/explore/model-performance",
            "docs/explore/project-recommendations",
            "docs/explore/dbt-explorer-faqs",
            {
              type: "category",
              label: "Потребление моделей",
              link: {
                type: "doc",
                id: "docs/explore/view-downstream-exposures",
              },
              items: [
                "docs/explore/view-downstream-exposures",
                "docs/explore/data-tile",
                "docs/explore/model-query-history",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Анализ с dbt Insights",
          link: { type: "doc", id: "docs/explore/dbt-insights" },
          items: [
            "docs/explore/dbt-insights", // main query page doc
            "docs/explore/navigate-dbt-insights", // navigate query page doc
            "docs/explore/access-dbt-insights", // info on how to access and use query page
          ],
        },
        {
          type: "category",
          label: "Документация проекта",
          link: {
            type: "doc",
            id: "docs/explore/build-and-view-your-docs",
          },
          items: ["docs/explore/build-and-view-your-docs"],
        },
      ],
    },
    {
      type: "category",
      label: "Использование семантического слоя dbt",
      collapsed: true,
      link: { type: "doc", id: "docs/use-dbt-semantic-layer/dbt-sl" },
      items: [
        "docs/use-dbt-semantic-layer/dbt-sl",
        {
          type: "link",
          label: "Быстрый старт с dbt Semantic Layer",
          href: `/guides/sl-snowflake-qs`,
        },
        {
          type: "category",
          label: "Настройка",
          link: { type: "doc", id: "docs/use-dbt-semantic-layer/setup-sl" },
          items: [
            "docs/use-dbt-semantic-layer/setup-sl",
            "docs/use-dbt-semantic-layer/sl-architecture",
          ],
        },
        {
          type: "category",
          label: "Развертывание метрик",
          link: { type: "doc", id: "docs/use-dbt-semantic-layer/deploy-sl" },
          items: [
            "docs/use-dbt-semantic-layer/deploy-sl",
            "docs/use-dbt-semantic-layer/exports",
            "docs/use-dbt-semantic-layer/sl-cache",
          ],
        },
        {
          type: "category",
          label: "Потребление",
          link: {
            type: "doc",
            id: "docs/use-dbt-semantic-layer/consume-metrics",
          },
          items: ["docs/use-dbt-semantic-layer/consume-metrics"],
        },
        "docs/use-dbt-semantic-layer/sl-faqs",
      ],
    },
    {
      type: 'html',
      value: 'dbt AI',
      className: 'sidebar-title',
    },
    {
      type: "category",
      label: "Copilot",
      collapsed: true,
      link: { type: "doc", id: "docs/cloud/dbt-copilot" },
      items: [
        "docs/cloud/dbt-copilot",
        "docs/cloud/enable-dbt-copilot",
        "docs/cloud/use-dbt-copilot",
        "docs/cloud/copilot-styleguide",
        "docs/cloud/copilot-chat-in-studio",
        "docs/cloud/dbt-copilot-faqs",
      ],
    },
    {
      type: "category",
      label: "dbt MCP",
      collapsed: true,
      link: { type: "doc", id: "docs/dbt-ai/about-mcp", },
      items: [
          "docs/dbt-ai/about-mcp",
          "docs/dbt-ai/setup-local-mcp",
          "docs/dbt-ai/setup-remote-mcp",
          "docs/dbt-ai/integrate-mcp-vscode",
          "docs/dbt-ai/integrate-mcp-cursor",
          "docs/dbt-ai/integrate-mcp-claude",
          ],
    },
    {
      type: 'html',
      value: 'Дополнительные инструменты',
      className: 'sidebar-title',
    },
    {
      type: "category",
      label: "Интеграции dbt",
      link: { type: "doc", id: "docs/cloud-integrations/overview" },
      items: [
        "docs/cloud-integrations/overview",
        {
          type: "category",
          label: "Визуализация и оркестрация экспозиций",
          link: {
            type: "doc",
            id: "docs/cloud-integrations/downstream-exposures",
          },
          items: [
            "docs/cloud-integrations/downstream-exposures",
            "docs/cloud-integrations/downstream-exposures-tableau",
            "docs/cloud-integrations/orchestrate-exposures",
          ],
        },
        {
          type: "category",
          label: "Нативное приложение Snowflake",
          link: {
            type: "doc",
            id: "docs/cloud-integrations/snowflake-native-app",
          },
          items: [
            "docs/cloud-integrations/snowflake-native-app",
            "docs/cloud-integrations/set-up-snowflake-native-app",
          ],
        },
        {
          type: "category",
          label: "Интеграции Semantic Layer",
          link: {
            type: "doc",
            id: "docs/cloud-integrations/avail-sl-integrations",
          },
          items: [
            "docs/cloud-integrations/avail-sl-integrations",
            "docs/cloud-integrations/semantic-layer/gsheets",
            "docs/cloud-integrations/semantic-layer/excel",
            "docs/cloud-integrations/semantic-layer/power-bi",
            "docs/cloud-integrations/semantic-layer/tableau",
          ],
        },
      ],
    },
    {
      type: 'html',
      value: 'О релизах dbt',
      className: 'sidebar-title',
    },
    {
      type: "category",
      label: "Доступные версии dbt",
      link: { type: "doc", id: "docs/dbt-versions/about-versions" },
      items: [
        "docs/dbt-versions/about-versions",
        "docs/dbt-versions/core",
        "docs/dbt-versions/cloud-release-tracks",
        "docs/dbt-versions/upgrade-dbt-version-in-cloud",
        "docs/dbt-versions/product-lifecycles",
        "docs/dbt-versions/experimental-features",
        {
          type: "category",
          label: "Гайды по обновлению версии dbt",
          link: {
            type: "generated-index",
            title: "Гайды по обновлению версии dbt",
            description: "Learn what's new in the latest version of dbt.",
            slug: "/docs/dbt-versions/core-upgrade",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "docs/dbt-versions/core-upgrade",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Что нового (Release Notes)",
      link: {
        type: "doc",
        id: "docs/dbt-versions/dbt-cloud-release-notes",
      },
      items: [
        "docs/dbt-versions/dbt-cloud-release-notes",
        "docs/dbt-versions/dbt-cloud-release-notes-gen",
        "docs/dbt-versions/compatible-track-changelog",
        "docs/dbt-versions/2024-release-notes",
        "docs/dbt-versions/2023-release-notes",
        "docs/dbt-versions/2022-release-notes",
        {
          type: "autogenerated",
          dirName: "docs/dbt-versions/release-notes",
        },
      ],
    },
    {
      type: 'html',
      value: ' ',
      className: 'sidebar-title',
    },
  ],
  apis: [
      "docs/dbt-cloud-apis/overview",
      {
        type: "category",
        label: "Доступ к API",
        link: { type: "doc", id: "docs/dbt-cloud-apis/authentication" },
        items: [
          "docs/dbt-cloud-apis/authentication",
          "docs/dbt-cloud-apis/user-tokens",
          "docs/dbt-cloud-apis/service-tokens",
        ],
      },
      {
        type: "category",
        label: "Административный API",
        link: { type: "doc", id: "docs/dbt-cloud-apis/admin-cloud-api" },
        items: [
          "docs/dbt-cloud-apis/admin-cloud-api",
          {
            type: "link",
            label: "API v2",
            href: "/dbt-cloud/api-v2",
          },
          {
            type: "link",
            label: "API v3",
            href: "/dbt-cloud/api-v3",
          },
        ],
      },
      {
        type: "category",
        label: "Discovery API",
        link: { type: "doc", id: "docs/dbt-cloud-apis/discovery-api" },
        items: [
          "docs/dbt-cloud-apis/discovery-api",
          "docs/dbt-cloud-apis/discovery-use-cases-and-examples",
          "docs/dbt-cloud-apis/project-state",
          "docs/dbt-cloud-apis/discovery-querying",
          {
            type: "category",
            label: "Схема",
            link: {
              type: "doc",
              id: "docs/dbt-cloud-apis/discovery-schema-about",
            },
            items: [
              "docs/dbt-cloud-apis/discovery-schema-about",
              {
                type: "category",
                label: "Окружение (рекомеднуется)",
                link: {
                  type: "doc",
                  id: "docs/dbt-cloud-apis/discovery-schema-environment",
                },
                items: [
                 "docs/dbt-cloud-apis/discovery-schema-environment",
                 {
                  type: "category",
                  label: "Applied",
                  link: {
                    type: "doc",
                    id: "docs/dbt-cloud-apis/discovery-schema-environment-applied",
                  },
                  items: [
                    "docs/dbt-cloud-apis/discovery-schema-environment-applied",
                    "docs/dbt-cloud-apis/discovery-schema-environment-applied-tests",
                    "docs/dbt-cloud-apis/discovery-schema-environment-applied-sources",
                    "docs/dbt-cloud-apis/discovery-schema-environment-applied-snapshots",
                    "docs/dbt-cloud-apis/discovery-schema-environment-applied-seeds",
                    "docs/dbt-cloud-apis/discovery-schema-environment-applied-resources",
                    "docs/dbt-cloud-apis/discovery-schema-environment-applied-models",
                    "docs/dbt-cloud-apis/discovery-schema-environment-applied-exposures",
                    "docs/dbt-cloud-apis/discovery-schema-environment-applied-exposure-tile",
                    "docs/dbt-cloud-apis/discovery-schema-environment-applied-tags",
                    "docs/dbt-cloud-apis/discovery-schema-environment-applied-packages",
                    "docs/dbt-cloud-apis/discovery-schema-environment-applied-owners",
                    "docs/dbt-cloud-apis/discovery-schema-environment-applied-modelHistoricalRuns",
                    "docs/dbt-cloud-apis/discovery-schema-environment-applied-lineage",
                  ],
                },
                  "docs/dbt-cloud-apis/discovery-schema-environment-definition",
                ],
              },
                // Uncomment to add Definition subpage, but need to make items non-empty
                // {
                //   type: "category",
                //   label: "Definition",
                //   items: [
                //     // insert pages here
                //   ],
                // },
              {
                type: "category",
                label: "Работа (Job)",
                link: {
                  type: "doc",
                  id: "docs/dbt-cloud-apis/discovery-schema-job",
                },
                items: [
                  "docs/dbt-cloud-apis/discovery-schema-job",
                  "docs/dbt-cloud-apis/discovery-schema-job-model",
                  "docs/dbt-cloud-apis/discovery-schema-job-models",
                  "docs/dbt-cloud-apis/discovery-schema-job-source",
                  "docs/dbt-cloud-apis/discovery-schema-job-sources",
                  "docs/dbt-cloud-apis/discovery-schema-job-seed",
                  "docs/dbt-cloud-apis/discovery-schema-job-seeds",
                  // "docs/dbt-cloud-apis/discovery-schema-job-snapshot",
                  "docs/dbt-cloud-apis/discovery-schema-job-snapshots",
                  "docs/dbt-cloud-apis/discovery-schema-job-test",
                  "docs/dbt-cloud-apis/discovery-schema-job-tests",
                  "docs/dbt-cloud-apis/discovery-schema-job-exposure",
                  "docs/dbt-cloud-apis/discovery-schema-job-exposures",
                  // "docs/dbt-cloud-apis/discovery-schema-job-macro",
                  // "docs/dbt-cloud-apis/discovery-schema-job-macros",
                ],
              },
            ],
          },
        ],
      },
      {
        type: "category",
        label: "API семантического слоя",
        link: { type: "doc", id: "docs/dbt-cloud-apis/sl-api-overview" },
        items: [
          "docs/dbt-cloud-apis/sl-api-overview",
          "docs/dbt-cloud-apis/sl-graphql",
          "docs/dbt-cloud-apis/sl-jdbc",
          "docs/dbt-cloud-apis/sl-python",
        ],
      },
  ],
  reference: [
    "reference/references-overview",
    {
      type: "category",
      label: "Конфигурация проекта",
      link: {
        type: "generated-index",
        title: "Конфигурация проекта",
        description: "The list of project configs available in dbt.",
        slug: "/category/project-configs"
      },
      collapsed: true,
      items: [
        "reference/dbt_project.yml",
        "reference/dbtignore",
        "reference/project-configs/analysis-paths",
        "reference/project-configs/asset-paths",
        "reference/project-configs/clean-targets",
        "reference/project-configs/config-version",
        "reference/project-configs/dispatch-config",
        "reference/project-configs/docs-paths",
        "reference/project-configs/function-paths",
        "reference/project-configs/macro-paths",
        "reference/project-configs/name",
        "reference/project-configs/on-run-start-on-run-end",
        "reference/project-configs/packages-install-path",
        "reference/project-configs/profile",
        "reference/project-configs/query-comment",
        "reference/project-configs/quoting",
        "reference/project-configs/require-dbt-version",
        "reference/project-configs/snapshot-paths",
        "reference/project-configs/seed-paths",
        "reference/project-configs/model-paths",
        "reference/project-configs/test-paths",
        "reference/project-configs/version",
      ],
    },
    {
      type: "category",
      label: "Конфигурация различных платформ",
      link: {
        type: "generated-index",
        title: "Конфигурации платформ данных",
        description:
          "Платформо-специфичные конфигурации используются для настройки проекта dbt под конкретную платформу базы данных.",
        slug: "/reference/resource-configs/resource-configs",
      },
      items: [
        "reference/resource-configs/azuresynapse-configs",
        "reference/resource-configs/athena-configs",
        "reference/resource-configs/impala-configs",
        "reference/resource-configs/spark-configs",
        "reference/resource-configs/bigquery-configs",
        "reference/resource-configs/clickhouse-configs",
        "reference/resource-configs/databricks-configs",
        "reference/resource-configs/deltastream-configs",
        "reference/resource-configs/doris-configs",
        "reference/resource-configs/duckdb-configs",
        "reference/resource-configs/fabric-configs",
        "reference/resource-configs/fabricspark-configs",
        "reference/resource-configs/firebolt-configs",
        "reference/resource-configs/greenplum-configs",
        "reference/resource-configs/infer-configs",
        "reference/resource-configs/ibm-netezza-config",
        "reference/resource-configs/materialize-configs",
        "reference/resource-configs/mssql-configs",
        "reference/resource-configs/mindsdb-configs",
        "reference/resource-configs/oracle-configs",
        "reference/resource-configs/postgres-configs",
        "reference/resource-configs/redshift-configs",
        "reference/resource-configs/singlestore-configs",
        "reference/resource-configs/snowflake-configs",
        "reference/resource-configs/trino-configs",
        "reference/resource-configs/starrocks-configs",
        "reference/resource-configs/data-cloud-configs",
        "reference/resource-configs/teradata-configs",
        "reference/resource-configs/upsolver-configs",
        "reference/resource-configs/vertica-configs",
        "reference/resource-configs/watsonx-presto-config",
        "reference/resource-configs/watsonx-spark-config",
        "reference/resource-configs/yellowbrick-configs",
      ],
    },
    {
      type: "category",
      label: "Конфигурация и свойства ресурсов",
      link: { type: "doc", id: "reference/resource-configs/resource-path" },
      items: [
        "reference/resource-configs/resource-path",
        {
          type: "category",
          label: "Конфигурация и свойства",
          link: {
            type: "doc",
            id: "reference/configs-and-properties",
          },
          items: [
            "reference/configs-and-properties",
            "reference/define-configs",
            "reference/define-properties",
          ],
        },
        {
          type: "category",
          label: "Общие свойства",
          link: {
            type: "generated-index",
            title: "Общие свойства",
            description: "Список общих свойств, доступных в dbt.",
          },
          items: [
            "reference/resource-properties/anchors",
            "reference/resource-properties/columns",
            "reference/resource-properties/config",
            "reference/resource-properties/constraints",
            "reference/resource-properties/deprecation_date",
            "reference/resource-properties/description",
            "reference/resource-properties/latest_version",
            "reference/resource-properties/data-tests",
            "reference/resource-properties/versions",
          ],
        },
        {
          type: "category",
          label: "Основные конфигурации",
          link: {
            type: "generated-index",
            title: "Общие конфигурации",
            description: "Список общих конфигураций, доступных в dbt.",
            slug: "/reference/general-configs",
          },
          items: [
            "reference/advanced-config-usage",
            "reference/resource-configs/access",
            "reference/resource-configs/alias",
            "reference/resource-configs/database",
            "reference/resource-configs/docs",
            "reference/resource-configs/enabled",
            "reference/resource-configs/event-time",
            "reference/resource-configs/full_refresh",
            "reference/resource-configs/grants",
            "reference/resource-configs/group",
            "reference/resource-configs/meta",
            "reference/resource-configs/persist_docs",
            "reference/resource-configs/plus-prefix",
            "reference/resource-configs/pre-hook-post-hook",
            "reference/resource-configs/schema",
            "reference/resource-configs/static-analysis",
            "reference/resource-configs/tags",
            "reference/resource-configs/unique_key",
          ],
        },
        {
          type: "category",
          label: "Для моделей",
          link: { type: "doc", id: "reference/model-properties" },
          items: [
            "reference/model-properties",
            "reference/model-configs",
            "reference/resource-configs/freshness",
            "reference/resource-configs/batch-size",
            "reference/resource-configs/begin",
            "reference/resource-properties/concurrent_batches",
            "reference/resource-configs/contract",
            "reference/resource-configs/lookback",
            "reference/resource-configs/materialized",
            "reference/resource-properties/model_name",
            "reference/resource-configs/on_configuration_change",
            "reference/resource-configs/sql_header",
          ],
        },
        {
          type: "category",
          label: "Для сидов (seeds)",
          link: { type: "doc", id: "reference/seed-properties" },
          items: [
            "reference/seed-properties",
            "reference/seed-configs",
            "reference/resource-configs/column_types",
            "reference/resource-configs/delimiter",
            "reference/resource-configs/quote_columns",
          ],
        },
        {
          type: "category",
          label: "Для снэпшотов (snapshots)",
          link: { type: "doc", id: "reference/snapshot-properties" },
          items: [
            "reference/snapshot-properties",
            "reference/snapshot-configs",
            "reference/resource-configs/snapshots-jinja-legacy",
            "reference/resource-configs/check_cols",
            "reference/resource-configs/dbt_valid_to_current",
            "reference/resource-configs/hard-deletes",
            "reference/resource-configs/invalidate_hard_deletes",
            "reference/resource-configs/snapshot_meta_column_names",
            "reference/resource-configs/snapshot_name",
            "reference/resource-configs/strategy",
            "reference/resource-configs/target_database",
            "reference/resource-configs/target_schema",
            "reference/resource-configs/updated_at",
          ],
        },
        {
          type: "category",
          label: "Для тестов данных",
          link: { type: "doc", id: "reference/data-test-configs" },
          items: [
            "reference/data-test-configs",
            "reference/resource-configs/fail_calc",
            "reference/resource-configs/limit",
            "reference/resource-configs/severity",
            "reference/resource-configs/store_failures",
            "reference/resource-configs/store_failures_as",
            "reference/resource-configs/where",
          ],
        },
        {
          type: "category",
          label: "Для юнит-тестов",
          link: { type: "doc", id: "reference/resource-properties/unit-tests" },
          items: [
            "reference/resource-properties/unit-tests",
            "reference/resource-properties/unit-test-input",
            "reference/resource-properties/data-formats",
            "reference/resource-properties/data-types",
            "reference/resource-properties/unit-testing-versions",
            "reference/resource-properties/unit-test-overrides",
          ],
        },
        {
          type: "category",
          label: "Для источников",
          link: { type: "doc", id: "reference/source-properties" },
          items: [
            "reference/source-properties",
            "reference/source-configs",
            "reference/resource-properties/database",
            "reference/resource-properties/external",
            "reference/resource-properties/freshness",
            "reference/resource-properties/identifier",
            "reference/resource-properties/loader",
            "reference/resource-properties/quoting",
            "reference/resource-properties/schema",
            "reference/resource-properties/overrides",
          ],
        },
        {
          type: "category",
          label: "Для analysis",
          link: { type: "doc", id: "reference/analysis-properties" },
          items: ["reference/analysis-properties"],
        },
        {
          type: "category",
          label: "Для экспозиций (exposures)",
          link: { type: "doc", id: "reference/exposure-properties" },
          items: ["reference/exposure-properties"],
        },
        {
          type: "category",
          label: "Для макросов",
          link: { type: "doc", id: "reference/macro-properties" },
          items: [
            "reference/macro-properties",
            "reference/resource-properties/arguments",
          ],
        },
        {
          type: "category",
          label: "Для функций",
          link: { type: "doc", id: "reference/function-properties" },
          items: [
            "reference/function-properties",
            "reference/function-configs",
            "reference/resource-configs/type",
            "reference/resource-configs/volatility",
            "reference/resource-configs/runtime-version",
            "reference/resource-configs/entry-point",
            "reference/resource-properties/returns",
            "reference/resource-properties/function-arguments",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Команды",
      link: { type: "doc", id: "reference/dbt-commands" },
      items: [
        "reference/dbt-commands",
        {
          type: "category",
          label: "Список команд",
          link: {
            type: "generated-index",
            title: "Список команд",
            description: "Список команд, доступных в dbt.",
            slug: "/reference/list-of-commands",
          },
          items: [
            "reference/commands/build",
            "reference/commands/clean",
            "reference/commands/clone",
            "reference/commands/cmd-docs",
            "reference/commands/compile",
            "reference/commands/debug",
            "reference/commands/deps",
            "reference/commands/dbt-environment",
            "reference/commands/init",
            "reference/commands/invocation",
            "reference/commands/list",
            "reference/commands/parse",
            "reference/commands/retry",
            "reference/commands/rpc",
            "reference/commands/run",
            "reference/commands/run-operation",
            "reference/commands/seed",
            "reference/commands/show",
            "reference/commands/snapshot",
            "reference/commands/source",
            "reference/commands/test",
            "reference/commands/version",
          ],
        },
        {
          type: "category",
          label: "Выбор узла (node)",
          link: { type: "doc", id: "reference/node-selection/syntax" },
          items: [
            "reference/node-selection/syntax",
            "reference/node-selection/exclude",
            "reference/node-selection/defer",
            "reference/node-selection/graph-operators",
            "reference/node-selection/set-operators",
            "reference/node-selection/methods",
            "reference/node-selection/putting-it-together",
            "reference/node-selection/yaml-selectors",
            "reference/node-selection/test-selection-examples",
            {
              type: "category",
              label: "О выборе состояния",
              link: {
                type: "doc",
                id: "reference/node-selection/state-selection",
              },
              items: [
                "reference/node-selection/state-selection",
                "reference/node-selection/configure-state",
                "reference/node-selection/state-comparison-caveats",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Флаги (глобальная конфигурация)",
          link: {
            type: "doc",
            id: "reference/global-configs/about-global-configs",
          },
          items: [
            "reference/global-configs/about-global-configs",
            "reference/global-configs/behavior-changes",
            {
              type: "category",
              label: "Изменение поведения адаптера",
              link: {
                type: "doc",
                id: "reference/global-configs/adapter-behavior-changes",
              },
              items: [
                "reference/global-configs/adapter-behavior-changes",
                "reference/global-configs/bigquery-changes",
                "reference/global-configs/databricks-changes",
                "reference/global-configs/redshift-changes",
                "reference/global-configs/snowflake-changes",
              ],
            },
            {
              type: "category",
              label: "Флаги настроек",
              link: {
                type: "generated-index",
                title: "Флаги настроек",
                description: "The flags you can set to configure dbt.",
                slug: "/reference/global-configs/setting-flags",
              },
              items: [
                "reference/global-configs/command-line-options",
                "reference/global-configs/environment-variable-configs",
                "reference/global-configs/project-flags",
              ],
            },
            {
              type: "category",
              label: "Доступные флаги",
              link: {
                type: "generated-index",
                title: "Доступные флаги",
                description: "Список флагов, доступных в dbt.",
                slug: "/reference/global-configs/available-flags",
              },
              items: [
                "reference/global-configs/usage-stats",
                "reference/global-configs/version-compatibility",
                "reference/global-configs/logs",
                "reference/global-configs/cache",
                "reference/global-configs/failing-fast",
                "reference/global-configs/indirect-selection",
                "reference/global-configs/json-artifacts",
                "reference/global-configs/parsing",
                "reference/global-configs/print-output",
                "reference/global-configs/record-timing-info",
                "reference/global-configs/resource-type",
                "reference/global-configs/static-analysis-flag",
                "reference/global-configs/warnings",
              ],
            },
          ],
        },
        "reference/events-logging",
        "reference/exit-codes",
        "reference/deprecations",
        "reference/parsing",
        "reference/programmatic-invocations",
      ],
    },
    {
      type: "category",
      label: "Руководство Jinja",
      link: {
        type: "generated-index",
        title: "Руководство Jinja",
        description: "Список функций Jinja, доступных в dbt.",
        slug: "/reference/jinja-reference",
      },
      items: [
        {
          type: "category",
          label: "Функции dbt Jinja",
          link: {
            type: "generated-index",
            title: "Функции dbt Jinja",
            description:
              "В дополнение к стандартной библиотеке Jinja мы добавили дополнительные функции и переменные в контекст Jinja, которые полезны при работе с проектом dbt.",
            slug: "/reference/dbt-jinja-functions",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "reference/dbt-jinja-functions",
            },
          ],
        },
        "reference/dbt-classes",
      ],
    },
    {
      type: "category",
      label: "Артефакты dbt",
      link: { type: "doc", id: "reference/artifacts/dbt-artifacts" },
      items: [
        "reference/artifacts/dbt-artifacts",
        "reference/artifacts/catalog-json",
        "reference/artifacts/manifest-json",
        "reference/artifacts/run-results-json",
        "reference/artifacts/sources-json",
        "reference/artifacts/sl-manifest",
        "reference/artifacts/other-artifacts",
      ],
    },
    {
      type: "category",
      label: "Разрешения в базе данных",
      link: {
        type: "doc",
        id: "reference/database-permissions/about-database-permissions",
      },
      items: [
        "reference/database-permissions/about-database-permissions",
        "reference/database-permissions/databricks-permissions",
        "reference/database-permissions/postgres-permissions",
        "reference/database-permissions/redshift-permissions",
        "reference/database-permissions/snowflake-permissions",
      ],
    },
  ],
  bestpractices: [
    {
      type: "category",
      label: "Лучшие практики",
      link: {
        type: "generated-index",
        title: "Гайды по лучшим практикам",
        description:
          "Узнайте, как dbt Labs подходит к созданию проектов, основываясь на наших актуальных взглядах на структуру, стиль и настройку.",
        slug: "best-practices",
      },
      items: [
        {
          type: "category",
          label: "Как мы структурируем наши проекты dbt",
          link: {
            type: "doc",
            id: "best-practices/how-we-structure/1-guide-overview",
          },
          items: [
            "best-practices/how-we-structure/2-staging",
            "best-practices/how-we-structure/3-intermediate",
            "best-practices/how-we-structure/4-marts",
            "best-practices/how-we-structure/5-the-rest-of-the-project",
          ],
        },
        {
          type: "category",
          label: "Как мы оформляем наши проекты dbt",
          link: {
            type: "doc",
            id: "best-practices/how-we-style/0-how-we-style-our-dbt-projects",
          },
          items: [
            "best-practices/how-we-style/1-how-we-style-our-dbt-models",
            "best-practices/how-we-style/2-how-we-style-our-sql",
            "best-practices/how-we-style/3-how-we-style-our-python",
            "best-practices/how-we-style/4-how-we-style-our-jinja",
            "best-practices/how-we-style/5-how-we-style-our-yaml",
            "best-practices/how-we-style/6-how-we-style-conclusion",
          ],
        },
        {
          type: "category",
          label: "Как мы создаем наши метрики",
          link: {
            type: "doc",
            id: "best-practices/how-we-build-our-metrics/semantic-layer-1-intro",
          },
          items: [
            "best-practices/how-we-build-our-metrics/semantic-layer-1-intro",
            "best-practices/how-we-build-our-metrics/semantic-layer-2-setup",
            "best-practices/how-we-build-our-metrics/semantic-layer-3-build-semantic-models",
            "best-practices/how-we-build-our-metrics/semantic-layer-4-build-metrics",
            "best-practices/how-we-build-our-metrics/semantic-layer-5-advanced-metrics",
            "best-practices/how-we-build-our-metrics/semantic-layer-6-terminology",
            "best-practices/how-we-build-our-metrics/semantic-layer-7-semantic-structure",
            "best-practices/how-we-build-our-metrics/semantic-layer-8-refactor-a-rollup",
            "best-practices/how-we-build-our-metrics/semantic-layer-9-conclusion",
          ],
        },
        {
          type: "category",
          label: "Как мы создаем наши проекты dbt Mesh",
          link: {
            type: "doc",
            id: "best-practices/how-we-mesh/mesh-1-intro",
          },
          items: [
            "best-practices/how-we-mesh/mesh-2-who-is-dbt-mesh-for",
            "best-practices/how-we-mesh/mesh-3-structures",
            "best-practices/how-we-mesh/mesh-4-implementation",
            "best-practices/how-we-mesh/mesh-6-coordinate-versions",  
            "best-practices/how-we-mesh/mesh-5-faqs",
          ],
        },
        {
          type: "category",
          label: "Лучшие практики материализации",
          link: {
            type: "doc",
            id: "best-practices/materializations/materializations-guide-1-guide-overview",
          },
          items: [
            "best-practices/materializations/materializations-guide-2-available-materializations",
            "best-practices/materializations/materializations-guide-3-configuring-materializations",
            "best-practices/materializations/materializations-guide-4-incremental-models",
            "best-practices/materializations/materializations-guide-5-best-practices",
            "best-practices/materializations/materializations-guide-6-examining-builds",
            "best-practices/materializations/materializations-guide-7-conclusion",
          ],
        },
        "best-practices/dont-nest-your-curlies",
        "best-practices/clone-incremental-models",
        "best-practices/writing-custom-generic-tests",
        "best-practices/best-practice-workflows",
        "best-practices/dbt-unity-catalog-best-practices",
      ],
    },
  ],
  community: [
    {
      type: "doc",
      id: "community/join",
    },
    {
      type: "category",
      label: "Внести вклад",
      link: {
        type: "doc",
        id: "community/contribute",
      },
      items: [
        {
          type: "doc",
          label: "Стать контрибьютером",
          id: "community/contribute",
        },
        "community/contributing/contributing-writing",
        "community/contributing/contributing-coding",
        "community/contributing/contributing-online-community",
        "community/contributing/contributing-realtime-events",
      ],
    },
    {
      type: "link",
      label: "Форум сообщества",
      href: "/community/forum",
    },
    {
      type: "link",
      label: "Мероприятия",
      href: "/community/events",
    },
    {
      type: "category",
      label: "Дополнительные ресурсы",
      items: [
        "community/resources/viewpoint",
        "community/resources/code-of-conduct",
        "community/resources/community-rules-of-the-road",
        "community/resources/maintaining-a-channel",
        "community/resources/forum-guidelines",
        "community/resources/getting-help",
        "community/resources/organizing-inclusive-events",
        "community/resources/contributor-expectations",
        "community/resources/oss-sa-projects",
        "community/resources/contributor-license-agreements",
        "community/resources/jobs-terms-and-conditions",
        "community/resources/speaking-at-a-meetup",
      ],
    },
  ],
  SQLReference: [
    {
      type: "category",
      label: "Справочник по SQL",
      link: {
        type: "generated-index",
        title: "Справочник по SQL",
        description:
          "Справочник по SQL — это собрание SQL-функций и ключевых слов, которые вы можете использовать в своей повседневной работе с данными.",
        slug: "/sql-reference",
      },
      items: [
        {
          type: "category",
          label: "Инструкции",
          items: [
            "sql-reference/statements/select",
            "sql-reference/statements/from",
            "sql-reference/statements/case",
            "sql-reference/statements/group-by",
            "sql-reference/statements/distinct",
          ],
        },
        {
          type: "category",
          label: "Функции агрегации",
          items: [
            "sql-reference/aggregate-functions/avg",
            "sql-reference/aggregate-functions/count",
            "sql-reference/aggregate-functions/max",
            "sql-reference/aggregate-functions/min",
            "sql-reference/aggregate-functions/round",
            "sql-reference/aggregate-functions/sum",
            "sql-reference/aggregate-functions/array-agg",
          ],
        },
        {
          type: "category",
          label: "Выражения",
          items: [
            "sql-reference/clauses/where",
            "sql-reference/clauses/having",
            "sql-reference/clauses/limit",
            "sql-reference/clauses/order-by",
          ],
        },
        {
          type: "category",
          label: "Работа с датами",
          items: [
            "sql-reference/date-functions/dateadd",
            "sql-reference/date-functions/datediff",
            "sql-reference/date-functions/datepart",
            "sql-reference/date-functions/datetrunc",
          ],
        },
        {
          type: "category",
          label: "Текстовые функции",
          items: [
            "sql-reference/string-functions/upper",
            "sql-reference/string-functions/lower",
            "sql-reference/string-functions/concat",
            "sql-reference/string-functions/trim",
          ],
        },
        {
          type: "category",
          label: "Оконные функции",
          items: [
            "sql-reference/window-functions/rank",
            "sql-reference/window-functions/row-number",
          ],
        },
        {
          type: "category",
          label: "Операторы",
          items: [
            "sql-reference/operators/between",
            "sql-reference/operators/in",
            "sql-reference/operators/or",
            "sql-reference/operators/ilike",
            "sql-reference/operators/like",
            "sql-reference/operators/and",
            "sql-reference/operators/not",
            "sql-reference/operators/any-all",
          ],
        },
        {
          type: "category",
          label: "Объединения",
          items: [
            "sql-reference/joins/inner-join",
            "sql-reference/joins/outer-join",
            "sql-reference/joins/self-join",
            "sql-reference/joins/cross-join",
            "sql-reference/joins/left-join",
            "sql-reference/joins/right-join",
          ],
        },
        {
          type: "category",
          label: "Типы данных",
          items: [
            "sql-reference/data-type/data-types",
            "sql-reference/data-type/strings",
          ],
        },
        {
          type: "category",
          label: "Другое",
          items: ["sql-reference/other/cast", "sql-reference/other/comments"],
        },
      ],
    },
  ],
  faqs: [
    {
      type: "category",
      label: "Часто задаваемые вопросы (FAQ)",
      link: {
        type: "generated-index",
        title: "Часто задаваемые вопросы (FAQ)",
        description:
          "Наш раздел Часто задаваемых вопросов (FAQ) - это место, где вы можете найти ответы на часто задаваемые вопросы (но мы рады ответить!). Если у вас есть вопрос или вы до сих пор не можете разобраться с чем-либо, просто свяжитесь с нами по электронной почте support@getdbt.com или нажмите на виджет чата, и мы сделаем все возможное, чтобы помочь.",
        slug: "/docs/faqs",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "faqs",
        },
      ],
    },
  ],
  support: [
    "docs/dbt-support",
    "docs/cloud/billing",
  ],
};

module.exports = sidebarSettings;
